config/routes.rb
Rails.application.routes.draw do
  # Health check
  get "up", to: "rails/health#show", as: :rails_health_check

  # Login
  get "/login", to: "users#signin"
  post "/login", to: "users#login"


  # Register
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"


  # Delete user
  delete "/user", to: "users#destroy"

  
  # New blog
  get "/newblog", to: "blogs#new"
  post "/blogs", to: "blogs#create"

  # Show all blogs
  get "/myblogs", to: "blogs#show"
  get "/blogs", to: "blogs#showall"

  # Show individual blog
  get "/blog/:id/edit", to: "blogs#edit", as: :editblog
  patch '/blog/:id/edit', to: 'blogs#update', as: :updateblog

  delete '/blog/:id', to: 'blogs#delete', as: :deleteblog


  get "/blog/:id", to: "blogs#each", as: :eachblog
  
  post '/blog/:id', to: "blogs#react", as: :reactblog

  post "/blog/:id/flag", to: "blogs#flagged", as: :flagblog


  post "blog/:id/comments", to: "comments#create", as: :createcomment
  delete "delete-comments/:id", to: "comments#destroy", as: :destroycomment

  post "blog/:id/save", to:"blogs#save", as: :saveblog_path

  patch "blog/:id/edit-comments", to: "comments#edit", as: :editcomment

  get "mysaved-blogs", to:"blogs#mysaved"


  # Root
  root "home#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments

  has_many :user_blog_reactions, dependent: :destroy

  has_many :reactions, through: :user_blog_reactions

  VALID_CHARACTERS_REGEX = /[^a-zA-Z0-9\s.,:':;"`&]/

  validates :title, presence: true, length: { minimum: 5, maximum: 100 }, format: { without: VALID_CHARACTERS_REGEX, message: "only allows letters, numbers, spaces, and .,:':;\"`&" }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }, format: { without: VALID_CHARACTERS_REGEX, message: "only allows letters, numbers, spaces, and .,:':;\"`&" }

  validate :no_special_characters_in_title
  validate :no_special_characters_in_description


  def reaction_count(reaction_id)
    user_blog_reactions.where(reaction_id: reaction_id).count
  end



  private
  def no_special_characters_in_title
    if title =~ VALID_CHARACTERS_REGEX
      errors.add(:title, "cannot contain special characters other than .,:':;\"`&")
    end
  end

  def no_special_characters_in_description
    if description =~ VALID_CHARACTERS_REGEX
      errors.add(:description, "cannot contain special characters other than .,:':;\"`&")
    end
  end

  

  before_update :validate_before_blog_update
  before_destroy :validate_before_blog_update


  # validates the user is allowed to edit or delete a blog
  def validate_before_blog_update
    if Current.user.id != self.user_id
      errors.add(:base, "You are not authorized to update this blog")
    end
  end


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController


  # unless these checks are verifies, all below methods are not called
  before_action :authenticate_user!
  

  # new blog creation get route calls this action
  def new
    @blog = Blog.new  
  end


  # returns only the blogs of a particular user
  def show
    @categories = Category.all
    @user = current_user

    if params[:category_id]
      @blogs = @user.blogs.where(category_id: params[:category_id])
    else
      @blogs = @user.blogs
    end
  end




  # returns all the blogs from the DB
  def showall
    @categories = Category.all
    @blogs = Blog.joins('LEFT JOIN user_blog_flags ON user_blog_flags.blog_id = blogs.id')
                 .where('user_blog_flags.flag IS NULL OR user_blog_flags.flag = ? OR user_blog_flags.user_id = ?', false, current_user.id)
  
                 
    if params[:category_id].present?
      @blogs = @blogs.where(category_id: params[:category_id])
    end

    if params[:search].present?
      search_query = "%#{params[:search].downcase}%"
      @blogs = @blogs.where('LOWER(blogs.title) LIKE ? ', search_query)
    end
   end

  

  # creates a new blog, post method calls this action
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path , notice: "Blog was successfully created."
    else
      render :new
    end 
  end


  # get edit route calls this action
  def edit
    @blog = Blog.find(params[:id])
  end


  def flagged
    blog_id = params[:blog_id]
    blog = Blog.find(blog_id)
   
    flagged_by = UserBlogFlag.find_by(blog_id: blog_id)
    if(flagged_by.present?)
      flagged_by.update(flag: !flagged_by.flag)
    else
      UserBlogFlag.create(user_id: blog.user_id, blog_id: blog_id, flag: true)
    end  
  end


  def mysaved
    user_id = current_user.id
    @saved_blogs = user_id.saved_blogs.includes(:blog)
  end
 

  def save
    blog_id = params[:blog_id]
    blog = Blog.find(blog_id)
  
    saved_by = SavedBlog.find_by(blog_id: blog_id, user_id: current_user.id)
    if saved_by.present?
      saved_by.update(saved: !saved_by.saved)
    else
      savedBlog = SavedBlog.new(blog_id: blog_id, user_id: current_user.id)
      if savedBlog.save
      else
        puts savedBlog.errors.full_messages
      end
    end
  end
  


  # post each blog route calls this  route for specific blog
  def each
    puts("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@2")
    @user_blog_reaction = UserBlogReaction.new
    @comment = Comment.new

    @blog = Blog.new
    @blog = Blog.find(params[:id])
    @reactions = Reaction.all
    @comments = @blog.comments
  end

  def react
  
    blog_id = params[:blog_id]
    blog = Blog.find(blog_id)
    user_id = blog.user_id
    

    blog_user_reaction = UserBlogReaction.new(
      user_id: user_id,
      blog_id: blog_id,
      reaction_id: params[:reaction]
    )
    if blog_user_reaction.save
      puts "BlogUserReaction saved successfully!"
      redirect_back fallback_location: root_path, notice: 'reaction was successfully added.'      
      
    else
      puts "Failed to save BlogUserReaction: #{blog_user_reaction.errors.full_messages.join(', ')}"    
      
    end 
  end
  
  

  # post update route calls this method
  def update
    @blog = Blog.find(params[:id])
    
    if @blog.update(blog_update_params)
      redirect_to eachblog_path(@blog), notice: "Blog updated successfully."
    else
      render :edit
    end
  end
  

  # update blog takes only these params
  def blog_update_params
    params.require(:blog).permit(:title, :description, :category_id)
  end


  # delete blog route calls this action for deleting the method
  def delete
   @blog = Blog.find_by(id: params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: "Blog was successfully deleted."
  end

  private 
  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :description,:category_id, :user_id)
  end

  


end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<% content_for :blog_css do %>
  <%= stylesheet_link_tag 'custom_styleSheet2', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>


<div class="blog-container" >
<div class="hi">
  <div class="blog-details">
    <h2> <%= blog.title %></h2>
    <p><%= blog.description %></p>
    <% category = Category.find_by(id: blog.category_id) %>
    <p>category : <%= category ? category.name : 'Uncategorized' %></p>
  </div>
  <div class="blog-actions">
  <% if current_user && current_user.id == blog.user_id %>
    <button><%= link_to "Edit", editblog_path(blog.id), class:"iamclass" %></button>
     <%= link_to "Delete", deleteblog_path(blog.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>
<%= link_to "Show this blog", eachblog_path(blog.id)%>
</div>

app/views/blogs/each.html.erb
<% if @user_blog_reaction.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @user_blog_reaction.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>



<h1><%= @blog.title %></h1>
<p><%= @blog.description %></p>
<% category = Category.find_by(id: @blog.category_id) %>
<p>Category: <%= category ? category.name : 'Uncategorized' %></p>

<div>
  <% @reactions.each do |reaction| %>
    <p>
      <%= button_to "#{reaction.name.capitalize} (#{@blog.reaction_count(reaction.id)})", reactblog_path(blog_id: @blog.id, reaction: reaction.id), class: "btn btn-primary" %>
    </p>
  <% end %>
  <% if @blog.user_id != current_user.id %>
  <%= button_to "flag", flagblog_path(blog_id: @blog.id), class: "btn btn-primary" %>
<% end %>

<% if @blog.user_id != current_user.id %>
  <%= button_to "save", saveblog_path_url(blog_id: @blog.id), class: "btn btn-primary" %>
<% end %>
  <div>
    <%= button_to "Comments", "#", id: "show-comment-form", class: "btn btn-primary" %>
  </div>

  <div id="comment-form" style="display: none;">
    <%= form_with(model: @comment, url: createcomment_url(blog_id: @blog.id), local: true) do |form| %>
      <div class="form-group">
        <%= form.label :content %>
        <%= form.text_area :content, class: "form-control" %>
      </div>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :blog_id, value: @blog.id %>
      <div class="form-group">
        <%= form.submit "Add Comment", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>


<div id="comments-section">
  <h2>Comments</h2>


  <% if @comment.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @comment.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>


<% if @comments.present? %>
  <% @comments.each do |comment| %>
  <div class="comment" id="comment-<%= comment.id %>">
    <div class="comment-content">
      <p class="fw-semibold text-success"><%= comment.content %></p>
    </div>
    <div class="comment-actions">
      <%= link_to 'Edit', '#', id: "show-edit-comment-form",class: "btn btn-primary edit-comment"%>
      <%= button_to 'Delete', destroycomment_path(comment.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </div>
    <div class="edit-comment-form" id="edit-comment-form" style="display: none;">
      
      <%= form_with(model: comment, url: editcomment_url(blog_id: @blog.id,comment_id: comment.id), local: true) do |form| %>
        <div class="form-group">
          <%= form.label :content %>
          <%= form.text_area :content, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.submit "Update", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    
    
   
  </div>
<% end %>
<% end %>
</div>





<%= button_to "Back to All Blogs", blogs_path, class: "btn btn-secondary" %>

<!-- Add this script to handle the form toggling -->
<script>
  document.addEventListener("DOMContentLoaded", function() {
    document.getElementById("show-comment-form").addEventListener("click", function(event) {
      event.preventDefault();
      var commentForm = document.getElementById("comment-form");
      if (commentForm.style.display === "none") {
        commentForm.style.display = "block";
      } else {
        commentForm.style.display = "none";
      }
    });
  });
  document.querySelectorAll(".edit-comment").forEach(function(editButton) {
    editButton.addEventListener("click", function(event) {
      event.preventDefault();
      var commentDiv = this.closest(".comment");
      var editForm = commentDiv.querySelector(".edit-comment-form"); 
      if (editForm.style.display === "none") {
        editForm.style.display = "block";
      } else {
        editForm.style.display = "none";
      }
    });
  });







  
  
</script>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= form_with(model: @blog, url: updateblog_path(@blog.id), local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
        <% @blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "Select a category", class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Blog', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
     
    </p>
  <% end %>
</div>

<%= link_to "New blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>Create a New Blog</h1>

<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
        <% @blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, prompt: 'Select Category', class: 'form-control' %>
  </div>

  <!-- Assuming you are setting the user_id based on the current logged-in user -->
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit 'Create Blog', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/show.html.erb
<h1>Blogs</h1>



<div class="categories">
  <% @categories.each do |category| %>
    
    <%= link_to category.name, myblogs_path(category_id: category.id), method: :get, class: "btn btn-warning btn-sm" %>
  
  <% end %>
  <%= button_to 'All', myblogs_path, method: :get, class: "btn btn-primary btn-sm" %>
</div>



<div id="blogs">
<% if @blogs.present? %>
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
    </p>
  <% end %>
  <% end %>
</div>

<%= link_to "New blog", newblog_path %>

app/views/blogs/showall.html.erb
<h1>Blogs</h1>



<div class="search">
  <%= form_with url: blogs_path, method: :get, local: true do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search blogs", class: "form-control" %>
    <%= submit_tag 'Search', class: "btn btn-primary btn-sm" %>
  <% end %>
</div>




<div class="categories">
  <% @categories.each do |category| %>
    
    <%= link_to category.name, blogs_path(category_id: category.id), method: :get, class: "btn btn-warning btn-sm" %>
  
  <% end %>
  <%= button_to 'All', blogs_path, method: :get, class: "btn btn-primary btn-sm" %>
</div>







<div id="blogs">
<% if @blogs.present? %>
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
    </p>
  <% end %>
  <% end %>
</div>

<%= link_to "New blog", newblog_path %>