config/routes.rb
Rails.application.routes.draw do
  # Health check
  get "up", to: "rails/health#show", as: :rails_health_check

  # Login
  get "/login", to: "users#signin"
  post "/login", to: "users#login"


  # Register
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"


  # Delete user
  delete "/user", to: "users#destroy"

  
  # New blog
  get "/newblog", to: "blogs#new"
  post "/blogs", to: "blogs#create"

  # Show all blogs
  get "/myblogs", to: "blogs#show"
  get "/blogs", to: "blogs#showall"

  # Show individual blog
  get "/blog/:id/edit", to: "blogs#edit", as: :editblog
  patch '/blog/:id/edit', to: 'blogs#update', as: :updateblog

  delete '/blog/:id', to: 'blogs#delete', as: :deleteblog


  get "/blog/:id", to: "blogs#each", as: :eachblog
  
  post '/blog/:id', to: "blogs#react", as: :reactblog

  post "/blog/:id/flag", to: "blogs#flagged", as: :flagblog


  post "blog/:id/comments", to: "comments#create", as: :createcomment
  delete "delete-comments/:id", to: "comments#destroy", as: :destroycomment

  post "blog/:id/save", to:"blogs#save", as: :saveblog_path

  patch "blog/:id/edit-comments", to: "comments#edit", as: :editcomment

  get "mysaved-blogs", to:"blogs#mysaved"


  # Root
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/views/home/_navbar.html.erb
  <% content_for :stylesheets do %>
    <%= stylesheet_link_tag 'custom_styleSheet1', media: 'all', 'data-turbolinks-track': 'reload' %>
  <% end %>


  
<div class="navbar">
  <%= link_to "Home", root_path %>
    <div class="hello">
      <% unless logged_in? %>
        <%= link_to "sign in", login_path %>
        <%= link_to "sign up", signup_path %>
      <% end %>
      <% if logged_in? %>
        <%= button_to "Logout", user_path, method: :delete %>
     <% end %>
    </div>
</div>

app/views/home/index.html.erb
<% content_for :stylesheets do %>
    <%= stylesheet_link_tag 'custom_styleSheet3', media: 'all', 'data-turbolinks-track': 'reload' %>
  <% end %>


  <div class="hero">
    <% if logged_in? %>
    <h1>Hi <%= current_user.username %></h1>
    <% end %>
    <h1>Welcome to Your Blog</h1>
    <p>Discover amazing content and share your own stories.</p>
    <%= link_to "Create Blog", newblog_path, class:"iamclass" %>
  </div>


  <div class="content">
    <h2>What is Your Blog?</h2>
    <p>Your Blog is a platform where you can find and share incredible stories, ideas, and experiences. Whether you're a writer, reader, or just someone looking for inspiration, Your Blog offers something for everyone.</p>
    <div class="features">
      <div class="feature">
        <h3>Explore</h3>
        <p>Browse through a variety of categories and topics to find content that interests you.</p>
      </div>
      <div class="feature">
        <h3>Create</h3>
        <p>Share your own stories and insights with our easy-to-use blogging tools.</p>
      </div>
      <div class="feature">
        <h3>Connect</h3>
        <p>Engage with a community of like-minded individuals and make meaningful connections.</p>
      </div>
    </div>
  </div>
  <footer>
    <p>&copy; 2024 Your Blog. All rights reserved.</p>
  </footer>